### ISSUE TITLE
Release without downloaded dependencies

### ISSUE THREAD

**Issue by adonnini** [oceanprotocol/secret-store-client-java#22]
Hi I need to use the secret-store-client-java for my Android Java application.

Having all dependent libraries of  secret-store-client-java packaged with the release, causes a significant problem because of conflict with dependencies of my application.

A solution that would work well would be to have a release of the  secret-store-client-java without the dependent libraries packaged with the release.

Would it be possible for you to produce such a release?

I apologize in advance if I misread the content of the  secret-store-client-java release jar.

Thanks,

Alex Donnini

**Comment by aaitor** [comment]
@adonnini , you can import any library in your project and exclude any transitive dependency using the standard package manager notation (i.e: if you use Maven you can use the `<exclusions>` notation

**Comment by adonnini** [comment]
Thanks. Sorry to have bothered you

**Comment by adonnini** [comment]
Hi,

Unfortunately, your suggestion to us the exclude command, in this case does not work.

I found another way around the issue.

Thanks anyway.
